# Generated by Django 4.2.7 on 2024-04-24 18:05

from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('referal_link', models.CharField(default=user.models.generate_random_string, editable=False, max_length=8, unique=True)),
                ('number_people', models.IntegerField(default=0)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('last_mining', models.IntegerField(default=0)),
                ('wallet_id_netbo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_identified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
                ('friend_referal_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.FloatField(default=0)),
                ('level2', models.FloatField(default=0)),
                ('level3', models.FloatField(default=0)),
                ('netbo', models.FloatField(default=0)),
                ('taim', models.IntegerField()),
                ('money_out', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_addres', models.CharField(max_length=200)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('is_identified', models.BooleanField(blank=True, null=True)),
                ('created_at', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Identified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=250)),
                ('serial_document', models.CharField(max_length=255)),
                ('id_image', models.ImageField(upload_to='identified/')),
                ('address_image', models.ImageField(upload_to='identified/')),
                ('selfie_image', models.ImageField(upload_to='identified/')),
                ('is_identified', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
